apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-lookup-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country-lookup-service
  template:
    metadata:
      labels:
        app: country-lookup-service
    spec:
      containers:
      - name: country-lookup-service
        image: country-lookup-service:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: country-lookup-service
spec:
  selector:
    app: country-lookup-service
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 6000
  type: LoadBalancer
